spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.JndiDataSourceAutoConfiguration
  datasource:
    jndi-name: null
    url: jdbc:postgresql://${DB_HOST:postgres}:${DB_PORT:5432}/${DB_NAME:hh_flow}
    username: ${DB_USER:hh_user}
    password: ${DB_PASSWORD:hh_password}
    driver-class-name: org.postgresql.Driver

  jta:
    enabled: false

  rabbitmq:
    host: ${RABBITMQ_HOST:rabbitmq}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASSWORD:guest}

  mail:
    host: ${MAIL_HOST:mailhog}
    port: ${MAIL_PORT:1025}
    properties:
      mail:
        smtp:
          auth: ${MAIL_SMTP_AUTH:false}
          starttls:
            enable: ${MAIL_SMTP_STARTTLS:false}

demo:
  rollback-vacancy-id: -1
