package com.example.hhflow.service;

import com.example.hhflow.domain.Resume;
import com.example.hhflow.dto.CreateResumeRequest;
import com.example.hhflow.exception.BusinessException;
import com.example.hhflow.exception.NotFoundException;
import com.example.hhflow.repository.ResumeRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.Clock;
import java.time.OffsetDateTime;
import java.util.List;
import java.util.Optional;

@Service
@RequiredArgsConstructor
public class ResumeService {

    private final ResumeRepository resumeRepository;
    private final Clock clock;

    @Transactional(readOnly = true)
    public List<Resume> findAll() {
        return resumeRepository.findAll();
    }

    @Transactional(readOnly = true)
    public Resume getById(Long id) {
        return resumeRepository.findById(id)
                .orElseThrow(() -> new NotFoundException("Resume not found: " + id));
    }

    @Transactional(readOnly = true)
    public Optional<Resume> findByCandidateId(Long candidateId) {
        return resumeRepository.findByCandidateId(candidateId);
    }

    @Transactional
    public Resume create(CreateResumeRequest request) {
        if (resumeRepository.findByCandidateId(request.getCandidateId()).isPresent()) {
            throw new BusinessException("Resume already exists for candidate: " + request.getCandidateId());
        }
        Resume resume = new Resume();
        resume.setCandidateId(request.getCandidateId());
        resume.setFullName(request.getFullName());
        resume.setSummary(request.getSummary());
        resume.setCreatedAt(OffsetDateTime.now(clock));
        return resumeRepository.save(resume);
    }

    @Transactional
    public Resume createAutogenerated(Long candidateId) {
        Resume resume = new Resume();
        resume.setCandidateId(candidateId);
        resume.setFullName("Auto-generated Candidate " + candidateId);
        resume.setSummary("Autogenerated resume by mocked subprocess");
        resume.setCreatedAt(OffsetDateTime.now(clock));
        return resumeRepository.save(resume);
    }
}
