package com.example.hhflow.service;

import com.example.hhflow.dto.request.CreateResumeRequest;
import com.example.hhflow.exception.BusinessException;
import com.example.hhflow.exception.NotFoundException;
import com.example.hhflow.model.Applicant;
import com.example.hhflow.model.Resume;
import com.example.hhflow.repository.ApplicantRepository;
import com.example.hhflow.repository.ResumeRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.Clock;
import java.time.OffsetDateTime;
import java.util.List;
import java.util.Optional;

@Service
@RequiredArgsConstructor
public class ResumeService {

    private final ResumeRepository resumeRepository;
    private final ApplicantRepository applicantRepository;
    private final Clock clock;

    @Transactional(readOnly = true)
    public List<Resume> findAll() {
        return resumeRepository.findAll();
    }

    @Transactional(readOnly = true)
    public Resume getById(Long id) {
        return resumeRepository.findById(id)
                .orElseThrow(() -> new NotFoundException("Resume not found: " + id));
    }

    @Transactional(readOnly = true)
    public Optional<Resume> findByCandidateId(Long candidateId) {
        return resumeRepository.findByApplicantId(candidateId);
    }

    @Transactional
    public Resume create(CreateResumeRequest request) {
        if (resumeRepository.findByApplicantId(request.getCandidateId()).isPresent()) {
            throw new BusinessException("Resume already exists for candidate: " + request.getCandidateId());
        }
        Applicant applicant = getOrCreateApplicant(request.getCandidateId());

        Resume resume = new Resume();
        resume.setApplicant(applicant);
        resume.setFullName(request.getFullName());
        resume.setSummary(request.getSummary());
        resume.setCreatedAt(OffsetDateTime.now(clock));
        return resumeRepository.save(resume);
    }

    @Transactional
    public Resume createAutogenerated(Long candidateId) {
        Applicant applicant = getOrCreateApplicant(candidateId);

        Resume resume = new Resume();
        resume.setApplicant(applicant);
        resume.setFullName("Auto-generated Candidate " + candidateId);
        resume.setSummary("Autogenerated resume by mocked subprocess");
        resume.setCreatedAt(OffsetDateTime.now(clock));
        return resumeRepository.save(resume);
    }

    private Applicant getOrCreateApplicant(Long candidateId) {
        return applicantRepository.findById(candidateId)
                .orElseGet(() -> {
                    Applicant applicant = new Applicant();
                    applicant.setId(candidateId);
                    return applicantRepository.save(applicant);
                });
    }
}
